Web/Models/ErrorViewModel.cs
using System;

namespace Web.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Web/Models/Medicine.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Models
{
	public class Medicine
	{
		public int Id { get; set; }

		[Required]
		public string Name { get; set; }

		[Display(Name = "Weight per dose [mg]")]
		public double WeightPerDose { get; set; }

		[Display(Name = "Amount of doses")]
		public int DoseAmount { get; set; }

		public string Composition { get; set; }

		public string Effect { get; set; }

		public string Dosage { get; set; }

		public string Indication { get; set; }

		public string Contraindication { get; set; }

		[Display(Name = "Price [zł]")]
		public decimal Price { get; set; }
	}
}

Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Models;

namespace Web.Controllers
{
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Web/Controllers/MedicinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Models;

namespace Web.Controllers
{
	public class MedicinesController : Controller
	{
		private IHttpClientFactory _clientFactory;

		public MedicinesController(IHttpClientFactory clientFactory)
		{
			this._clientFactory = clientFactory;
			
		}

		public IActionResult Index()
		{
			IEnumerable<Medicine> medicines = null;

			using (var client = this._clientFactory.CreateClient())
			{
				client.BaseAddress = new Uri(string.Format("{0}://{1}{2}/api/", Request.Scheme, Request.Host, Request.PathBase));
				var responseTask = client.GetAsync("medicines");
				responseTask.Wait();

				var result = responseTask.Result;
				if (result.IsSuccessStatusCode)
				{
					var readTask = result.Content.ReadAsAsync<IList<Medicine>>();
					readTask.Wait();

					medicines = readTask.Result;
				}
				else
				{
					medicines = Enumerable.Empty<Medicine>();
					ModelState.AddModelError(string.Empty, "Server error");
				}
			}

			return View(medicines);
		}

		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create(Medicine medicine)
		{
			using (var client = this._clientFactory.CreateClient())
			{
				client.BaseAddress = new Uri(string.Format("{0}://{1}{2}/api/", Request.Scheme, Request.Host, Request.PathBase));
				var postTask = client.PostAsJsonAsync<Medicine>("medicines", medicine);
				postTask.Wait();

				var result = postTask.Result;
				if (result.IsSuccessStatusCode)
				{
					return RedirectToAction("Index");
				}
			}

			ModelState.AddModelError(string.Empty, "Server Error");
			return View(medicine);
		}

		public IActionResult Details(int id)
		{
			Medicine medicine = null;

			using (var client = this._clientFactory.CreateClient())
			{
				client.BaseAddress = new Uri(string.Format("{0}://{1}{2}/api/", Request.Scheme, Request.Host, Request.PathBase));

				var responseTask = client.GetAsync("medicines/" + id.ToString());
				responseTask.Wait();

				var result = responseTask.Result;
				if (result.IsSuccessStatusCode)
				{
					var readTask = result.Content.ReadAsAsync<Medicine>();
					readTask.Wait();

					medicine = readTask.Result;
				}
			}

			return View(medicine);
		}

		public IActionResult Edit(int id)
		{
			Medicine medicine = null;

			using (var client = this._clientFactory.CreateClient())
			{
				client.BaseAddress = new Uri(string.Format("{0}://{1}{2}/api/", Request.Scheme, Request.Host, Request.PathBase));

				var responseTask = client.GetAsync("medicines/" + id.ToString());
				responseTask.Wait();

				var result = responseTask.Result;
				if (result.IsSuccessStatusCode)
				{
					var readTask = result.Content.ReadAsAsync<Medicine>();
					readTask.Wait();

					medicine = readTask.Result;
				}
			}

			return View(medicine);
		}

		[HttpPost]
		public IActionResult Edit(int id, Medicine medicine)
		{
			using (var client = this._clientFactory.CreateClient())
			{
				client.BaseAddress = new Uri(string.Format("{0}://{1}{2}/api/", Request.Scheme, Request.Host, Request.PathBase));

				var putTask = client.PutAsJsonAsync<Medicine>("medicines/" + id.ToString(), medicine);
				putTask.Wait();

				var result = putTask.Result;
				if (result.IsSuccessStatusCode)
				{
					return RedirectToAction("Index");
				}
			}

			return View(medicine);
		}

		public IActionResult Delete(int id)
		{
			using (var client = this._clientFactory.CreateClient())
			{
				client.BaseAddress = new Uri(string.Format("{0}://{1}{2}/api/", Request.Scheme, Request.Host, Request.PathBase));

				var deleteTask = client.DeleteAsync("medicines/" + id.ToString());
				deleteTask.Wait();

				var result = deleteTask.Result;
				if (result.IsSuccessStatusCode)
				{
					return RedirectToAction("Index");
				}
			}

			return RedirectToAction("Index");
		}
	}
}

Web/Controllers/api/MedicinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Web.Models;

namespace Web.Controllers.api
{
    [Route("api/[controller]")]
    [ApiController]
    public class MedicinesController : ControllerBase
    {
        private readonly DiagnosticsContext _context;

        public MedicinesController(DiagnosticsContext context)
        {
            _context = context;
        }

        // GET: api/Medicines
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Medicine>>> GetMedicine()
        {
            return await _context.Medicine.ToListAsync();
        }

        // GET: api/Medicines/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Medicine>> GetMedicine(int id)
        {
            var medicine = await _context.Medicine.FindAsync(id);

            if (medicine == null)
            {
                return NotFound();
            }

            return medicine;
        }

        // PUT: api/Medicines/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutMedicine(int id, Medicine medicine)
        {
            if (id != medicine.Id)
            {
                return BadRequest();
            }

            _context.Entry(medicine).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MedicineExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Medicines
        [HttpPost]
        public async Task<ActionResult<Medicine>> PostMedicine(Medicine medicine)
        {
            _context.Medicine.Add(medicine);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetMedicine", new { id = medicine.Id }, medicine);
        }

        // DELETE: api/Medicines/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Medicine>> DeleteMedicine(int id)
        {
            var medicine = await _context.Medicine.FindAsync(id);
            if (medicine == null)
            {
                return NotFound();
            }

            _context.Medicine.Remove(medicine);
            await _context.SaveChangesAsync();

            return medicine;
        }

        private bool MedicineExists(int id)
        {
            return _context.Medicine.Any(e => e.Id == id);
        }
    }
}

Web/Views/Medicines/Create.cshtml
@model Web.Models.Medicine

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Medicine</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WeightPerDose" class="control-label"></label>
                <input asp-for="WeightPerDose" class="form-control" />
                <span asp-validation-for="WeightPerDose" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoseAmount" class="control-label"></label>
                <input asp-for="DoseAmount" class="form-control" />
                <span asp-validation-for="DoseAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Composition" class="control-label"></label>
                <input asp-for="Composition" class="form-control" />
                <span asp-validation-for="Composition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Effect" class="control-label"></label>
                <input asp-for="Effect" class="form-control" />
                <span asp-validation-for="Effect" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dosage" class="control-label"></label>
                <input asp-for="Dosage" class="form-control" />
                <span asp-validation-for="Dosage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Indication" class="control-label"></label>
                <input asp-for="Indication" class="form-control" />
                <span asp-validation-for="Indication" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contraindication" class="control-label"></label>
                <input asp-for="Contraindication" class="form-control" />
                <span asp-validation-for="Contraindication" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Views/Medicines/Details.cshtml
@model Web.Models.Medicine

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Medicine</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.WeightPerDose)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.WeightPerDose)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.DoseAmount)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.DoseAmount)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Composition)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Composition)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Effect)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Effect)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Dosage)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Dosage)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Indication)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Indication)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Contraindication)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Contraindication)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Web/Views/Medicines/Edit.cshtml
@model Web.Models.Medicine

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Medicine</h4>
<hr />
<div class="row">
    <div class="col-md-7">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WeightPerDose" class="control-label"></label>
                <input asp-for="WeightPerDose" class="form-control" />
                <span asp-validation-for="WeightPerDose" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoseAmount" class="control-label"></label>
                <input asp-for="DoseAmount" class="form-control" />
                <span asp-validation-for="DoseAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Composition" class="control-label"></label>
                <textarea asp-for="Composition" class="form-control" ></textarea>
                <span asp-validation-for="Composition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Effect" class="control-label"></label>
                <textarea asp-for="Effect" class="form-control" ></textarea>
                <span asp-validation-for="Effect" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dosage" class="control-label"></label>
                <textarea asp-for="Dosage" class="form-control" ></textarea>
                <span asp-validation-for="Dosage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Indication" class="control-label"></label>
                <textarea asp-for="Indication" class="form-control" ></textarea>
                <span asp-validation-for="Indication" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contraindication" class="control-label"></label>
                <textarea asp-for="Contraindication" class="form-control" ></textarea>
                <span asp-validation-for="Contraindication" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Views/Medicines/Index.cshtml
@model IEnumerable<Web.Models.Medicine>

@{
    ViewData["Title"] = "Index";
}

<h1>Medicines</h1>

<p>
    <a asp-action="Create">Create New Medicine</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WeightPerDose)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoseAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Composition)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Effect)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dosage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Indication)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contraindication)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WeightPerDose)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoseAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Composition)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Effect)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dosage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Indication)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contraindication)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Diagnostics</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Medicines" asp-action="Index">Medicines</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Diagnostics
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>